### ISSUE TITLE
FR: "howto" get bundleId?

### ISSUE THREAD

**Issue by r2evans** [Nauxscript/app-switcher-spoon#1]
I recognize this is likely mac-generic, but it's not abundantly clear to me the best/canonical ways to get bundle Ids and window names. For instance, one window I like to be able to switch to is simply "R" (yes, that's the whole window name). I haven't been using this spoon long enough to know for certain, but I fear that can bite me when I have other windows with titles that contain an upper-case "R".

(Further, not sure if HS supports this, but ... that window is a graphics canvas created by the R programming language. The underlying executable comes from the `R.app`, but calling that app is not the same as the window with the "R" title. Is there a way to more clearly identify windows that can be much more specific, like a window class? Or can we use regex for window titles, so `"^R$"` would work for me here?)

Thanks for the spoon!

**Comment by Nauxscript** [comment]
Here's the English translation:

Hey! Thanks for your feedback!
There are simple ways to get the bundle ID:
1. Using the command line: Run `osascript -e 'id of app "Application Name"'` to output the corresponding bundle ID. For example: `osascript -e 'id of app "Safari"'`
2. Or you can right-click the application in Applications folder, select "Show Package Contents", then find the `CFBundleIdentifier` in `Contents/info.plist` file - this is the bundle ID (Note: this method requires you to have software installed that can open plist files to view their contents).

Regarding your second question, since I haven't used R language, I can't speak to that aspect. However, it seems your question is: "When an application has multiple windows open, is it possible to open a specific window (based on window name) using custom hotkeys?"
From what I understand, Hammerspoon should have APIs that can get all windows opened by an app, and then filter them based on specific conditions (simple string matching or regex matching). Theoretically, it should be possible to get the specific window you want.
However, due to my limited knowledge of Hammerspoon and Lua programming, I can only answer this far - I apologize for that. If you're willing, you're welcome to submit a PR to help improve this functionality. I believe this would be a very useful feature.

**Comment by Nauxscript** [comment]
Hey! Thanks for your feedback!

There are simple ways to get the bundle ID:
1. Using the command line: Run `osascript -e 'id of app "Application Name"'` to output the corresponding bundle ID. For example: `osascript -e 'id of app "Safari"'`
2. Or you can right-click the application in Applications folder, select "Show Package Contents", then find the `CFBundleIdentifier` in `Contents/info.plist` file - this is the bundle ID (Note: this method requires you to have software installed that can open plist files to view their contents).

Regarding your second question, since I haven't used R language, I can't speak to that aspect. However, it seems your question is: "When an application has multiple windows open, is it possible to open a specific window (based on window name) using custom hotkeys?"
From what I understand, Hammerspoon should have APIs that can get all windows opened by an app, and then filter them based on specific conditions (simple string matching or regex matching). Theoretically, it should be possible to get the specific window you want.
However, due to my limited knowledge of Hammerspoon and Lua programming, I can only answer this far - I apologize for that. If you're willing, you're welcome to submit a PR to help improve this functionality. I believe this would be a very useful feature.

**Comment by r2evans** [comment]
Thanks for the feedback, that's helpful. I'm new to macos and new to HS, so a double-whammy trying to appease my muscle-memory coming from my previous laptop. This is definitely helpful, though personally I find macos hides a lot of really easy/useful information behind obscure APIs and command line interfaces. All of my years of windows/linux administration are not very insightful here on this shiny new mac :-/

FYI, I suggest it might be very useful to some users if you put something like that call to `osascript` in the documentation. If I'm the first since you started, then maybe I'm wrong, but I suspect it could help _somebody_. :-)

**Comment by Nauxscript** [comment]
Thank you for your suggestion. I will update the documentation to help others who might have similar questions. The main reason for creating this project was that I originally had a dedicated software called `Manico` (in case you need similar functionality like I did) to achieve this effect, but after updating my macOS version, the software temporarily stopped working. So I created this spoon, and initially didn't expect others would be interested in it, but habitually made the repository public. Perhaps this is the true spirit of open source: "Maybe this could be useful for others!" Therefore, I really appreciate your suggestion, which has given me a deeper understanding of open source and the idea of "doing something beneficial for others." Thank you again, and have a great day :)

**Comment by r2evans** [comment]
heh, I just realized that this repo is not the same spoon as https://github.com/Hammerspoon/Spoons/tree/master/Source/AppWindowSwitcher.spoon, sorry for assuming you were the author/maintainer of the published spoon :-)
